### DISCUSSION TITLE
[lion-button] Text gets selected on multiple clicks

### DISCUSSION THREAD

**Discussion by Biswajee** [ing-bank/lion#1157] [Ideas]
Double clicking on button [here](https://lion-web-components.netlify.app/?path=/docs/buttons-button--main) selects the button text. Below code might be useful [here](https://github.com/ing-bank/lion/blob/679d189ec4c8b6b568b13a0c9898a3b4e9feb4a7/packages/button/src/LionButton.js#L54) 😄  
```css
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
}
```
