### ISSUE TITLE
[input-datepicker] Wrong styles of the invoker button when `readonly` or `disabled`

### ISSUE THREAD

**Issue by bashmish** [ing-bank/lion#123]
![image](https://user-images.githubusercontent.com/137844/59852265-c3130500-936e-11e9-9302-7b0ac1578d78.png)

I found out why there is a difference between how disabled and readonly buttons looks like

for disabled we have this style:

```css
            :host(.state-disabled) .input-group ::slotted(*) {
              color: var(--disabled-text-color, #adadad);
            }
```

not for readonly though

this is just a side-effect of course, there was no intention to make a different colour of the button, but it is a bug, because in both cases the button should look like disabled and in both cases we need consistent styles which we just don't define and face a strange inconsistent side effect

_Originally posted by @bashmish in https://github.com/ing-bank/lion/pull/105#discussion_r295801113
